### PR TITLE
Create toggle switch for light/dark theme

### PR DESCRIPTION
**Pull request by kimdomenick**
- Add JS script to detect and store user theme preferences
- Add toggle button so that user can change theme
- Adjust styles

### CODE REVIEW

**Comment by raubin** [comment]
@kimdomenick - It's looking good, but it needs some logic to detect initial OS dark mode settings. When I loaded it, the toggle indicated I was using light mode when my OS is using dark mode, so the first time I toggled it, it did nothing.

**Comment by kimdomenick** [comment]
@raubin - I just pushed an updated JS file which fixed the initial page load issue for me.

**Comment by kimdomenick** [comment]
Hmm... thinking about this more, and I need to make some additional tweaks (beyond just setting a default mode).

**Comment by kimdomenick** [comment]
@raubin - give that latest commit a whirl and let me know what you think.

**Comment by raubin** [comment]
@kimdomenick - it's properly detecting my OS settings on first visit, and then updating if I change my OS settings after first visit. The problem is it doesn't retain my override settings when I use the toggle. From a UX standpoint, I think a user would expect that the toggle would be honored once set. What do you think? 

To handle that, you could rely on OS settings only if local storage value isn't set, and otherwise always use the local storage value.

**Comment by kimdomenick** [comment]
@raubin - when you've got a minute, please review again and see comments in the script.  :)

**Comment by raubin** [comment]
@kimdomenick - sorry, I know this one is taking some time, but we're not quite there yet. With local storage values deleted and my OS set to light mode i'm still getting the dark mode theme, but with the toggle set to light mode. Happy to jump on a call to go through with you, if that would be helpful.

**Comment by kimdomenick** [comment]
@raubin -we're gonna get so much karma for this PR.  New commit.  Try again, please.

**Comment by raubin** [comment]
houston, we have lift off! 🚀 /approved

**Pull request merged**
