### PR TITLE
Redesign and refactor Color Cube interface (HTML/JS/SASS)

### PR DESCRIPTION
**Pull request by jhogue**
Big redesign. Went with a dark theme as the colors seem to stand out better in general. Eventually making it a user-choice would be nice. 

* Remove Brunch and update Readme instructions
* Remove Bourbon/Neat
* Update to the latest SASS library from Grey-Matter
* Refactor some HTML and styles
* Add support for a third row of results — AAA, AA and AAA large, AA large
* Add better visual feedback for pass/fail grades
* Add Oomph logo and preferred fonts

Resolves Issue #19. 

Screen Shot 2019-10-28 at 12 39 50 PM

### CODE REVIEW

**Comment by kbeck303** [comment]
This works nicely! This part feels a little weird, can we add the font sizes for the other `AA` and `AAA`

**Comment by kbeck303** [comment]
I also feel like the `AA` and `AAA` and font-size could use a little design love.

**Comment by kbeck303** [comment]
We could probably remove the `24px` all together if we add an example above the results with the more detailed explanation of the different levels. What do you think?

**Comment by jhogue** [comment]
I'm not following. The example I was sort of following is this site: https://contrastchecker.com/ The circles are nice and clear, but would be difficult with multiple colors in a list. I also realized that both AA and AAA18pt use the same 4.5 criteria, so I grouped them together. But maybe that is what is throwing you off?

**Comment by jhogue** [comment]
Imma gonna merge this. Any objections?

**Pull request merged**
